use_frameworks!

platform :ios, '8.0'

target 'NXKit_Example' do
  pod 'NXKit', :path => '../'

  target 'NXKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
